export const TITLE_TERMS_CONDITIONS = 'ACH Payment Authorization Terms and Conditions';

export const TERMS_CONDITIONS =
  "I authorize regularly scheduled charges to my checking/savings account. I will be charged the amount indicated each billing period. A receipt for each payment will be provided to me, and the charge will appear on my bank statement as an 'ACH Debit.' I agree that no prior notification will be provided unless the date or amount changes, in which case I will receive notice from Cubework at least 10 days prior to the payment being collected.\n" +
  'I authorize Cubework to charge my bank account indicated for the specified amount on the first day of each month. If the first day of the month falls on a weekend, the charge will be applied on the last prior business day.\n' +
  'I authorize the total due upon execution to be charged as an initial payment with the account information provided during sign-up.\n' +
  'This payment is for the months of security deposit, prorated license fee, and other applicable charges as specified during the sign-up process.\n' +
  'I understand that this authorization will remain in effect until I cancel it in writing, and I agree to notify Cubework in writing of any changes in my account information or termination of this authorization at least 30 days prior to the next billing date. If the above noted payment dates fall on a weekend or holiday, I understand that the payments may be executed on the next business day. For ACH debits to my checking/savings account, I understand that because these are electronic transactions, these funds may be withdrawn from my account as soon as the above noted periodic transaction dates. Payment for the total due, if authorized, will take place on the signing date of this form, unless specified elsewhere.\n' +
  'In the case of an ACH Transaction being rejected for Non-Sufficient Funds (NSF) I understand that Cubework may at its discretion attempt to process the charge again within 30 days, and agree to an additional $100.00 charge for each attempt returned NSF which will be initiated as a separate transaction from the authorized recurring payment. I acknowledge that the origination of ACH transactions to my account must comply with the provisions of U.S. law. I certify that I am an authorized user of this bank account and will not dispute these scheduled transactions with my bank; so long as the transactions correspond to the terms indicated in this authorization form.\n' +
  "For licensees enrolled in recurring ACH payments, only one payment rejection due to NSF will be permitted. In the case when payment is rejected two months consecutively, or a total of three instances (within a year), the licensee must clear their outstanding balance through money order, cashier's check, credit card or wire transfer (no personal check). Additionally, the licensee's agreement will be terminated at the end of the month. The licensee will have the option to redraft an agreement with an additional 2 months worth of prepaid license fees and 1 month security deposit. The licensee will no longer qualify for auto-ACH payments. If licensee disagrees with the terms stated, they will be required to clear the payment and move out within 30 days.\n" +
  'For licensees enrolled in ACH for promotional areas, additional security deposit will be charged in the event the licensee requests removal of ACH. Security deposit charged will be adjusted to match the policy outlined in Section 7 of the License Agreement.\n' +
  'By clicking "I Agree" or by providing your bank account information, you acknowledge that you have read, understood, and agree to these terms and conditions for ACH payment authorization.\n';

export const TITLE_CC_TERMS_CONDITIONS = 'Credit Card Authorization Form License Agreement Terms and Conditions';

export const CC_TERMS_CONDITIONS =
  'Credit Card Authorization Form License Agreement Terms and Conditions\n' +
  'I hereby authorize CUBEWORK INC. to charge my credit card for agreed upon total due (including, but not limited to the license fee and security deposit). The rate will be at the current rate and terms at the time of the transaction. I understand that my information will be saved to file for future transactions on my account.\n' +
  'I (WE) HEREBY AUTHORIZE CUBEWORK INC. TO MAKE CHARGES TO MY CREDIT CARD, AND, IF NECESSARY, INITIATE ADJUSTMENTS FOR ANY TRANSACTIONS CREDITED/DEBITED IN ERROR. I AGREE THAT THOSE CHARGES WILL BE MADE ACCORDING TO MY USE OF SERVICES AND THAT TO TERMINATE THE BILLING PROCESS I MUST EITHER CANCEL MY ACCOUNT, OR ARRANGE FOR AN ALTERNATIVE METHOD OF PAYMENT. I UNDERSTAND THAT ALL ACCOUNT CANCELLATIONS MUST BE MADE IN WRITING ACCORDING TO THE REQUIREMENTS OF “CUBEWORK INC.“\n' +
  "I (WE) AGREE THAT I WILL NOT DISPUTE “CUBEWORK, INC'S“ CHARGES WITH MY CREDIT CARD ISSUER SO LONG AS THE AMOUNT IN QUESTION WAS FOR SERVICES/PRODUCTS RENDERED PRIOR TO MY CANCELLING MY ACCOUNT IN THE MANNER REQUIRED BY THE TERMS OF SERVICE.\n" +
  'I (WE) GUARANTEE THAT I AM THE LEGAL CARDHOLDER FOR THIS CREDIT CARD, AND THAT I AM LEGALLY AUTHORIZED TO ENTER INTO THIS BILLING AGREEMENT WITH “CUBEWORK, INC. “\n' +
  'I (WE) UNDERSTAND THAT CREDIT CARD PAYMENTS INCUR A PROCESSING FEE OF 3.5% FOR ALL CREDIT CARD PROVIDERS, AND AGREE TO PAY FOR THE PROCESSING FEE IN ADDITION TO THE ORIGINAL CHARGE.\n' +
  'By clicking "I Agree" or adding my credit card information, I acknowledge that I have read, understood, and agree to these terms and conditions.\n';
